### ISSUE TITLE
remote access support

### ISSUE THREAD

**Issue by lvelvee** [alexmojaki/heartrate#9]
https://github.com/alexmojaki/heartrate/blob/7fa29d9d5b2f72fdab98a1349efa5dfc784ab78a/heartrate/core.py#L86

**Comment by alexmojaki** [comment]
Can you expand on what happened when you tried setting the `host` argument?

I can't remember why I added that line or what happens without it. I know that I tried changing things when playing with #7 and it didn't go well. Can you make a PR and test that it works both locally and remotely?

**Comment by lvelvee** [comment]
I guess you added this line due to `url_for` from flask, it need SERVER_NAME to return correct url.
I'm glad to make the PR.
